package com.hhuneau.asobi.mtg.sets.booster;

public enum SlotType {
    CHECKLIST, COMMON, DOUBLE_FACED, DOUBLE_FACED_COMMON, DOUBLE_FACED_MYTHIC_RARE,
    DOUBLE_FACED_RARE, DOUBLE_FACED_UNCOMMON, LAND, MARKETING, MYTHIC_RARE, RARE,
    TIMESHIFTED_COMMON, TIMESHIFTED_PURPLE, TIMESHIFTED_RARE, TIMESHIFTED_UNCOMMON, UNCOMMON,
    FOIL, MASTERPIECE
}
